/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVacanciesRouteImport } from './routes/app.vacancies'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRequirementsRouteImport } from './routes/app.requirements'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppInterviewsRouteImport } from './routes/app.interviews'
import { Route as AppHelpdeskRouteImport } from './routes/app.helpdesk'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppAuditLogsRouteImport } from './routes/app.audit-logs'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppApplicationsRouteImport } from './routes/app.applications'
import { Route as AppAiCenterRouteImport } from './routes/app.ai-center'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVacanciesRoute = AppVacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequirementsRoute = AppRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskRoute = AppHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vacancies': typeof AppVacanciesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vacancies': typeof AppVacanciesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/bills': typeof AppBillsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/interviews': typeof AppInterviewsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/requirements': typeof AppRequirementsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vacancies': typeof AppVacanciesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/applications'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/interviews'
    | '/app/payments'
    | '/app/profile'
    | '/app/reports'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vacancies'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/applications'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/interviews'
    | '/app/payments'
    | '/app/profile'
    | '/app/reports'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vacancies'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/applications'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/audit-logs'
    | '/app/bills'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/interviews'
    | '/app/payments'
    | '/app/profile'
    | '/app/reports'
    | '/app/requirements'
    | '/app/settings'
    | '/app/vacancies'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacancies': {
      id: '/app/vacancies'
      path: '/vacancies'
      fullPath: '/app/vacancies'
      preLoaderRoute: typeof AppVacanciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requirements': {
      id: '/app/requirements'
      path: '/requirements'
      fullPath: '/app/requirements'
      preLoaderRoute: typeof AppRequirementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interviews': {
      id: '/app/interviews'
      path: '/interviews'
      fullPath: '/app/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/helpdesk': {
      id: '/app/helpdesk'
      path: '/helpdesk'
      fullPath: '/app/helpdesk'
      preLoaderRoute: typeof AppHelpdeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-center': {
      id: '/app/ai-center'
      path: '/ai-center'
      fullPath: '/app/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBillsRoute: typeof AppBillsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpdeskRoute: typeof AppHelpdeskRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRequirementsRoute: typeof AppRequirementsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVacanciesRoute: typeof AppVacanciesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiCenterRoute: AppAiCenterRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBillsRoute: AppBillsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpdeskRoute: AppHelpdeskRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRequirementsRoute: AppRequirementsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVacanciesRoute: AppVacanciesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
